AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Ubuntu 24.04 LTS, Claude Code, Playwright, tmux, and git

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type (t3.medium has 4GB RAM required for Claude Code)
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - m5.large
      - m5.xlarge

  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: IP address range allowed to SSH to the instance (CIDR notation)
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid CIDR range like x.x.x.x/x

  GitHubRepo:
    Type: String
    Default: ''
    Description: Optional GitHub repo URL to clone (e.g., https://github.com/user/repo)

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Claude Code EC2 instance
      GroupName: !Sub 'claude-code-sg-${AWS::StackName}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub 'claude-code-sg-${AWS::StackName}'

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: '{{resolve:ssm:/aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id}}'
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !GetAtt EC2SecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex

          # Update system packages
          apt-get update
          apt-get upgrade -y

          # Install git and tmux
          apt-get install -y git tmux curl unzip

          # Install Node.js 20 LTS (required for Playwright)
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

          # Install Claude Code for ubuntu user
          sudo -u ubuntu bash << 'EOF'
          cd /home/ubuntu
          curl -fsSL https://claude.ai/install.sh | bash

          # Add claude to PATH in .bashrc if not already there
          if ! grep -q 'claude' ~/.bashrc; then
            echo 'export PATH="$HOME/.claude/bin:$PATH"' >> ~/.bashrc
          fi
          EOF

          # Install Playwright with Chromium for ubuntu user
          sudo -u ubuntu bash << 'EOF'
          cd /home/ubuntu
          npm install -D @playwright/test@latest
          npx playwright install chromium
          EOF

          # Install Playwright system dependencies
          npx --yes playwright install-deps chromium

          # Install beads (bd) task tracking CLI
          curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash

          # Add beads to ubuntu user's PATH
          sudo -u ubuntu bash << 'EOF'
          if ! grep -q '.beads/bin' ~/.bashrc; then
            echo 'export PATH="$HOME/.beads/bin:$PATH"' >> ~/.bashrc
          fi
          EOF

          # Install agent-deck (Claude Code session manager)
          sudo -u ubuntu bash << 'EOF'
          curl -fsSL https://raw.githubusercontent.com/asheshgoplani/agent-deck/main/install.sh | bash
          EOF

          # Create CLAUDE.md with instructions in .claude directory
          sudo -u ubuntu mkdir -p /home/ubuntu/.claude
          sudo -u ubuntu tee /home/ubuntu/.claude/CLAUDE.md > /dev/null << 'CLAUDEMD'
          # Claude Instructions

          ## Task Tracking

          Use 'bd' for task tracking.

          ### Beads (bd)

          Task management CLI for tracking work and dependencies.

          ### Commands

          - bd init - Initialize beads in repo (use --stealth for local-only)
          - bd ready - Show tasks with no blockers
          - bd create "Title" -p <priority> - Create task (-p 0 = highest)
          - bd dep add <child> <parent> - Link dependencies
          - bd show <id> - View task details

          ## Browser Testing

          Use Playwright for headless browser testing. Chromium is pre-installed.

          ### Quick Test Script

          Create a test file and run with: npx playwright test

          ### Example Usage

          ```javascript
          const { chromium } = require('@playwright/test');
          const browser = await chromium.launch();
          const page = await browser.newPage();
          await page.goto('http://localhost:3000');
          await page.screenshot({ path: 'screenshot.png' });
          await browser.close();
          ```
          CLAUDEMD

          # Clone GitHub repo and initialize beads if provided
          GITHUB_REPO="${GitHubRepo}"
          if [ -n "$GITHUB_REPO" ]; then
            REPO_NAME=$(basename "$GITHUB_REPO" .git)
            sudo -u ubuntu git clone "$GITHUB_REPO" /home/ubuntu/$REPO_NAME
            sudo -u ubuntu bash -c "cd /home/ubuntu/$REPO_NAME && bd init"
          fi

          # Signal completion
          echo "Installation complete" > /home/ubuntu/setup-complete.txt
          chown ubuntu:ubuntu /home/ubuntu/setup-complete.txt

      Tags:
        - Key: Name
          Value: !Sub 'claude-code-instance-${AWS::StackName}'

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i <your-key.pem> ubuntu@${EC2Instance.PublicIp}'
