AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Amazon Linux 2023, Claude Code, tmux, and git

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access

  InstanceType:
    Type: String
    Default: t3.medium
    Description: EC2 instance type (t3.medium has 4GB RAM required for Claude Code)
    AllowedValues:
      - t3.medium
      - t3.large
      - t3.xlarge
      - m5.large
      - m5.xlarge

  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: IP address range allowed to SSH to the instance (CIDR notation)
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid CIDR range like x.x.x.x/x

  GitHubRepo:
    Type: String
    Default: ''
    Description: Optional GitHub repo URL to clone (e.g., https://github.com/user/repo)

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Claude Code EC2 instance
      GroupName: !Sub 'claude-code-sg-${AWS::StackName}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub 'claude-code-sg-${AWS::StackName}'

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !GetAtt EC2SecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -ex

          # Update system packages
          dnf update -y

          # Install git and tmux
          dnf install -y git tmux

          # Install Claude Code for ec2-user
          sudo -u ec2-user bash << 'EOF'
          cd /home/ec2-user
          curl -fsSL https://claude.ai/install.sh | bash

          # Add claude to PATH in .bashrc if not already there
          if ! grep -q 'claude' ~/.bashrc; then
            echo 'export PATH="$HOME/.claude/bin:$PATH"' >> ~/.bashrc
          fi
          EOF

          # Install beads (bd) task tracking CLI
          curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash

          # Add beads to ec2-user's PATH
          sudo -u ec2-user bash << 'EOF'
          if ! grep -q '.beads/bin' ~/.bashrc; then
            echo 'export PATH="$HOME/.beads/bin:$PATH"' >> ~/.bashrc
          fi
          EOF

          # Install agent-deck (Claude Code session manager)
          sudo -u ec2-user bash << 'EOF'
          curl -fsSL https://raw.githubusercontent.com/asheshgoplani/agent-deck/main/install.sh | bash
          EOF

          # Create CLAUDE.md with beads instructions in .claude directory
          sudo -u ec2-user mkdir -p /home/ec2-user/.claude
          sudo -u ec2-user tee /home/ec2-user/.claude/CLAUDE.md > /dev/null << 'CLAUDEMD'
          # Claude Instructions

          ## Task Tracking

          Use 'bd' for task tracking.

          ### Beads (bd)

          Task management CLI for tracking work and dependencies.

          ### Commands

          - bd init - Initialize beads in repo (use --stealth for local-only)
          - bd ready - Show tasks with no blockers
          - bd create "Title" -p <priority> - Create task (-p 0 = highest)
          - bd dep add <child> <parent> - Link dependencies
          - bd show <id> - View task details
          CLAUDEMD

          # Clone GitHub repo and initialize beads if provided
          GITHUB_REPO="${GitHubRepo}"
          if [ -n "$GITHUB_REPO" ]; then
            REPO_NAME=$(basename "$GITHUB_REPO" .git)
            sudo -u ec2-user git clone "$GITHUB_REPO" /home/ec2-user/$REPO_NAME
            sudo -u ec2-user bash -c "cd /home/ec2-user/$REPO_NAME && bd init"
          fi

          # Signal completion
          echo "Installation complete" > /home/ec2-user/setup-complete.txt
          chown ec2-user:ec2-user /home/ec2-user/setup-complete.txt

      Tags:
        - Key: Name
          Value: !Sub 'claude-code-instance-${AWS::StackName}'

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i <your-key.pem> ec2-user@${EC2Instance.PublicIp}'
